version: "2"

#networks:
#  app-tier:
#    driver: bridge

services:
  postgres:
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
